import XLSX from 'xlsx';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

// ---- Customers / Fleet ----
const wb1 = XLSX.readFile(path.join(root, 'Customers with Truck and or Cameras-2026-08-03-01-09-39.xlsx'));
const rows1 = XLSX.utils.sheet_to_json(wb1.Sheets[wb1.SheetNames[0]], { header: 1, defval: '' });
const providers = [];
let current = null;

for (let i = 10; i < rows1.length; i++) {
  const r = rows1[i];
  const c1 = String(r[1] || '').trim();
  const c2 = String(r[2] || '').trim();
  const truck = String(r[3] || '').trim();
  const rfid = String(r[4] || '').trim();
  const field3 = String(r[5] || '').trim();

  if (c1 === 'Subtotal' && c2 === 'Count') {
    if (current) {
      current.truckCount = Number(r[3]) || current.trucks.length;
      current.trucksWithRFID = current.trucks.filter(t => t.rfid).length;
      current.trucksWithoutRFID = current.truckCount - current.trucksWithRFID;
      providers.push(current);
      current = null;
    }
    continue;
  }

  if (c1 === 'Grand Total') break;

  if (c1 && c1 !== 'Grand Total' && !c1.startsWith('Subtotal')) {
    current = { serviceProvider: c1, trucks: [] };
    if (truck) current.trucks.push({ name: truck, rfid, field3 });
  } else if (current && truck) {
    current.trucks.push({ name: truck, rfid, field3 });
  }
}

// ---- Missing WO ----
const wb2 = XLSX.readFile(path.join(root, 'Missing WO-2026-08-03-01-05-34.xlsx'));
const rows2 = XLSX.utils.sheet_to_json(wb2.Sheets[wb2.SheetNames[0]], { header: 1, defval: '' });
const wos = [];
let lastType = '';
let lastSeg = '';

for (let i = 13; i < rows2.length; i++) {
  const r = rows2[i];
  const type = String(r[1] || '').trim();
  const seg = String(r[2] || '').trim();
  const wo = String(r[4] || '').trim();

  if (type === 'Subtotal' || seg === 'Subtotal' || type === 'Total' || type === 'Grand Total' || String(r[3]).trim() === 'Count') continue;
  if (!wo) continue;
  if (type) lastType = type;
  if (seg && seg !== 'Count') lastSeg = seg;
  if (!lastType || !lastSeg) continue;

  wos.push({
    requestType: lastType,
    segment: lastSeg,
    woNumber: wo,
    assetName: String(r[5] || '').trim(),
    serviceDay: String(r[6] || '').trim(),
    accountNumber: String(r[7] || '').trim(),
    address: String(r[8] || '').trim(),
    routeNumber: String(r[9] || '').trim(),
    dispatchNumber: String(r[10] || '').trim(),
    createdBy: String(r[11] || '').trim(),
    requestDate: String(r[12] || '').trim(),
    dueDate: String(r[13] || '').trim(),
    caseAge: Number(r[14]) || 0,
    lastAttempt: String(r[15] || '').trim(),
    notes: String(r[16] || '').trim(),
  });
}

console.log('providers', providers.length);
console.log('total trucks', providers.reduce((s, p) => s + p.truckCount, 0));
console.log('with RFID', providers.reduce((s, p) => s + p.trucksWithRFID, 0));
console.log('WOs', wos.length);

const out = `// ============================================================
// Excel Data — Parsed from:
// 1. Customers with Truck and/or Cameras
// 2. Missing Work Orders (Edmonton AB)
// Auto-generated by scripts/generateExcelData.mjs — do not hand-edit
// ============================================================

export const truckFleetData = ${JSON.stringify(providers, null, 2)};

export const missingWorkOrders = ${JSON.stringify(wos, null, 2)};

// ============================================================
// Computed Summaries
// ============================================================

export const fleetSummary = (() => {
  const totalProviders = truckFleetData.length;
  const totalTrucks = truckFleetData.reduce((s, p) => s + p.truckCount, 0);
  const trucksWithRFID = truckFleetData.reduce((s, p) => s + p.trucksWithRFID, 0);
  const trucksWithoutRFID = truckFleetData.reduce((s, p) => s + p.trucksWithoutRFID, 0);
  const rfidCoverage = totalTrucks ? ((trucksWithRFID / totalTrucks) * 100).toFixed(1) : '0.0';
  const top5Providers = [...truckFleetData].sort((a, b) => b.truckCount - a.truckCount).slice(0, 5);
  const providersBySize = [...truckFleetData].sort((a, b) => b.truckCount - a.truckCount);
  const largestGap = [...truckFleetData].sort((a, b) => b.trucksWithoutRFID - a.trucksWithoutRFID)[0] || null;
  return { totalProviders, totalTrucks, trucksWithRFID, trucksWithoutRFID, rfidCoverage, top5Providers, providersBySize, largestGap };
})();

export const woSummary = (() => {
  const totalWOs = missingWorkOrders.length;
  const avgCaseAge = totalWOs ? Math.round(missingWorkOrders.reduce((s, w) => s + w.caseAge, 0) / totalWOs) : 0;
  const maxCaseAge = totalWOs ? Math.max(...missingWorkOrders.map(w => w.caseAge)) : 0;
  const minCaseAge = totalWOs ? Math.min(...missingWorkOrders.map(w => w.caseAge)) : 0;
  const overdueWOs = missingWorkOrders.filter(w => w.caseAge > 700).length;

  const byRequestType = {};
  missingWorkOrders.forEach(w => {
    if (!byRequestType[w.requestType]) byRequestType[w.requestType] = { count: 0, totalAge: 0 };
    byRequestType[w.requestType].count++;
    byRequestType[w.requestType].totalAge += w.caseAge;
  });
  const requestTypeBreakdown = Object.entries(byRequestType).map(([type, data]) => ({
    type,
    count: data.count,
    avgAge: Math.round(data.totalAge / data.count),
  })).sort((a, b) => b.count - a.count);

  const byDispatch = {};
  missingWorkOrders.forEach(w => {
    if (!byDispatch[w.dispatchNumber]) byDispatch[w.dispatchNumber] = 0;
    byDispatch[w.dispatchNumber]++;
  });
  const dispatchBreakdown = Object.entries(byDispatch).map(([dispatch, count]) => ({ dispatch, count })).sort((a, b) => b.count - a.count);

  return { totalWOs, avgCaseAge, maxCaseAge, minCaseAge, overdueWOs, requestTypeBreakdown, dispatchBreakdown };
})();

export function getProvider(name) {
  return truckFleetData.find(p => p.serviceProvider.toLowerCase() === String(name || '').toLowerCase());
}

export function providerId(name) {
  return 'SP-' + String(name).replace(/[^a-zA-Z0-9]+/g, '-');
}
`;

fs.writeFileSync(path.join(root, 'src', 'excelData.js'), out);
console.log('wrote src/excelData.js');
